### ISSUE TITLE
Sample report?

### ISSUE THREAD

**Issue by mwarkentin** [aws-samples/ecs-chargeback-cloudformation#1]
@awssteph This looks really interesting.. cost allocation for our ECS tasks has been a long pain point of ours. It looks like there's a decent bit of set up to get this working, so I was curious if you have a sample report that you could publish so that we could see how the solution works before implementing ourselves?

Thanks!

**Comment by awssteph** [comment]
Hey, thats a great point, I will add to repo and then let you know :)

**Comment by mwarkentin** [comment]
Awesome, thanks!

**Comment by awssteph** [comment]
See screen shot at the bottom, let me know if there is any clarification needed

**Comment by mwarkentin** [comment]
Thanks @awssteph - let me know if I'm reading this right:

* `task_usage`: total use of an instance by the running task over a month
* `total_usage`: total capacity of the instance the task was running on for a month
* `percent`: `task_usage / total_usage`
* `ec2_cost`: monthly cost for EC2 instance in $
* Not clear on the difference between `services` and `service_name`, they look to be the same value?
* `tag`: Value of specified tag for the ECS service (could be `App`, `TeamID`, etc?)

I was curious what the "limiting" factor for EC2 usage is in this report? Eg. our cluster and tasks are generally memory constrained which drives our cluster size, but others may be CPU - is there a way to specify which is the case for your cluster? 

Edit: Might be helpful to have a small section in the docs where each of the report fields are defined and described.

**Comment by awssteph** [comment]
Hey, good feedback i have added to the below of the readme and changed the code to have arn rather than service name twice. 
Currently this is just using GB usage rather than CPU
